server:
  port: ${PORT:8791}
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/paymentservicedb
    username: sa
    password:
  application:
    name: payment-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
